[package]
name = "cranedrop"
version = "0.1.0"
edition = "2021"

[dependencies.bevy]
version = "0.15"
default-features = false
features = [
    "dynamic_linking",
    "bevy_core_pipeline",
    "bevy_winit",
    #"multi_threaded",
]
